version: '3'
services:
  web:
    build: app
    volumes:
      - static_vol:/opt/app/static
      - media_vol:/opt/app/media
    env_file:
      - ./.env
    depends_on:
     - db

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_vol:/opt/app/static
      - media_vol:/opt/app/media
    ports:
      - 80:80
    depends_on:
      - web

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yaml:/swagger.yaml
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - nginx


volumes:
  media_vol:
  static_vol:
  postgres_data: